search_algorithm: local_search # Options: local_search, iterative_local_search, simulated_annealing, pso, ga
cost_function: schwefel # Options: sphere, schwefel, schaffer, griewank, func7, func8, func9, func11, revenue
x_initial: null # A d-dimensional list, such as [1.0, -1.0], or null. If null, the x_initial will be a random point in the domain.

local_search:
    max_itr: 300
    convergence_threshold: 0.001
